# 组织设置
"organization-wiki-management":
  icon: settings
  sort: 7
  organization: # 组织层的菜单
    - "space": # 菜单字段
        icon: book  # 菜单图标
        Routes: /wiki/space # 菜单对应路由
        sort: 1 # 菜单的次序
        permission: # 菜单内容具有的权限
          - 'wiki-service.wiki-organization-space.pageByOptions'
          - 'wiki-service.wiki-organization-space.create'
          - 'wiki-service.wiki-organization-space.query'
          - 'wiki-service.wiki-organization-space.update'
          - 'wiki-service.wiki-organization-space.checkName'
          - 'wiki-service.wiki-organization-space.delete'
          - 'wiki-service.wiki-organization-space.sync'


# 项目设置
"project-wiki-management":
  icon: settings
  sort: 7
  project:
    - "space":
        icon: book
        Routes: /wiki/space
        sort: 1
        permission:
          - 'wiki-service.wiki-project-space.create'
          - 'wiki-service.wiki-project-space.checkName'
          - 'wiki-service.wiki-project-space.pageByOptions'
          - 'wiki-service.wiki-project-space.query'
          - 'wiki-service.wiki-project-space.update'
          - 'wiki-service.wiki-project-space.delete'
          - 'wiki-service.wiki-project-space.sync'

  # site: # site层的菜单
  # user: # 个人中心层的菜单
