"organization-wiki-management": "Wiki management"
"project-wiki-management": "Wiki management"

# site
# organization
"organization-wiki-management.space": "Wiki space"
"global.menusetting.icon": "space icon"


# project
"project-wiki-management.space": "Wiki space"

# user

