"rentsetting": "组织设置"
"prosetting": "项目设置"
"organization-wiki-management": "Wiki管理"
"project-wiki-management": "Wiki管理"

# site
# organization
"rentsetting.wiki-management": "Wiki管理"
"organization-wiki-management.space": "Wiki空间"
"global.menusetting.icon": "空间图标"

# project
"prosetting.wiki-management": "Wiki管理"
"project-wiki-management.space": "Wiki空间"

# user

