"organization-wiki-management": "Wiki管理"
"project-wiki-management": "Wiki管理"

# site
# organization
"organization-wiki-management.space": "Wiki空间"
"global.menusetting.icon": "空间图标"

# project
"project-wiki-management.space": "Wiki空间"

# user
